version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    open-pull-requests-limit: 0 # Zero PRs means that only security updates will be triggered
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "uxio0"

  - package-ecosystem: docker
    directory: "/docker/web"
    open-pull-requests-limit: 0 # Zero PRs means that only security updates will be triggered
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "uxio0"

  - package-ecosystem: github-actions
    open-pull-requests-limit: 0 # Zero PRs means that only security updates will be triggered
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "uxio0"
