version: '3'

services:
  nginx:
    image: nginx:1.13
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - nginx-shared:/safe-nginx
    depends_on:
      - web
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    working_dir: /safe_service
    command: scripts/run_web.sh
    ports:
      - "27017"
    volumes:
      - nginx-shared:/safe-nginx
volumes:
  nginx-shared:
