version: '3'

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:1.13-alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - nginx-shared:/safe-nginx
    depends_on:
      - web
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    working_dir: /app
    ports:
      - "27017"
    volumes:
      - nginx-shared:/safe-nginx
    command: docker/web/run_web.sh
