# Generated by Django 2.0.4 on 2018-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='push_token',
            field=models.TextField(verbose_name='push_token'),
        ),
    ]
