# Generated by Django 2.1.2 on 2018-10-09 09:48

import django_eth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_auto_20180423_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=django_eth.models.EthereumAddressField(primary_key=True, serialize=False),
        ),
    ]
