# Generated by Django 2.1.2 on 2018-10-09 09:48

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_auto_20180423_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=gnosis.eth.django.models.EthereumAddressField(primary_key=True, serialize=False),
        ),
    ]
