# Generated by Django 2.1.7 on 2019-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0004_auto_20181009_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ios', models.BooleanField(default=False)),
                ('android', models.BooleanField(default=True)),
                ('web', models.BooleanField(default=True)),
            ],
        ),
    ]
