# Generated by Django 2.2.2 on 2019-06-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0007_auto_20190415_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='web',
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='extension',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='android',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='ios',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
