# Generated by Django 2.2.2 on 2019-06-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0007_auto_20190415_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtype',
            old_name='web',
            new_name='extension',
        ),
    ]
