# Generated by Django 2.2.2 on 2019-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0008_auto_20190625_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='android',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='extension',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='ios',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
